plugins {
	id 'java'
	id 'groovy'
}

group = 'com.hoya'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '24'
}

jar {
	manifest {
		attributes 'Main-Class': 'com.hoya.algorithm.Main'
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
}

dependencies {

	compileOnly("org.projectlombok:lombok:1.18.38")
	annotationProcessor("org.projectlombok:lombok:1.18.38")

	testCompileOnly("org.projectlombok:lombok:1.18.38")
	testAnnotationProcessor("org.projectlombok:lombok:1.18.38")
	// Spock Test dependencies
	testImplementation 'org.spockframework:spock-core:2.4-M6-groovy-4.0'

}

tasks.named('test') {''
	useJUnitPlatform()
}
